# Site settings
title: Content Negotiation
email: comments@bigbluehat.com
description: > # this means to ignore newlines until "baseurl:"
  Content negotiation is a mechanism defined in the HTTP specification that
  makes it possible to serve different versions of a document (or more
  generally, a resource representation) at the same URI, so that user agents
  can specify which version fit their capabilities the best.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: conneg
github_username:  conneg

# Build settings
markdown: kramdown
